name: MinTotp Gem
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Build:
    name: Unit Test
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: bundle install --jobs=3 --retry=3
      - run: bundle exec rake spec
